            Title Practica 4          ;TITULO



DATOS SEGMENT PARA PUBLIC DATA
SEGMENTO1 DB  2,4,6,8,10,12,14,2,8,12
SEGMENTO2 DB  2,4,6,8,10,12,14,8,6,4
SEGMENTORES DB 10 DUP('?')

DATOS ENDS 
 
 
 
PILA SEGMENT PARA STACK 'STACK'
    DB 64 DUP('STACK')     
PILA ENDS



CODIGO SEGMENT PARA PUBLIC 'CODE'
INICIO PROC FAR
    
    
    
    PUSH DS
    MOV AX,0
    PUSH AX
    MOV AX, DATOS
    MOV DS, AX
    MOV ES, AX 
    
    
MOV CX,10
LEA SI,SEGMENTO1  
LEA BX,SEGMENTO2
LEA DI,SEGMENTORES
 
 
;MULTIPLICACIONES DE LOS SEGMENTOS 1 Y 2  
REPITE: 
MOV AL,[SI] 
MUL [BX]
MOV [DI],AL     ;GUARDA LA MULTIPLICACION DENTRO DEL SEGMENTO 

INC SI
INC BX    
INC DI
DEC CX
JNZ REPITE

         
;AL ACABAR LA MULTIPLICACION RESTABLECE LOS VALORES Y TOMA DE NUEVO EL SEGMENTO 1          
MOV CX,10 
LEA SI,SEGMENTORES 
LEA BX,SEGMENTO2
LEA DI,SEGMENTO1

REPITEDIV:
MOV AL,[SI]
DIV [BX] 
MOV [DI],AL


INC SI
INC BX    
INC DI
DEC CX
JNZ REPITEDIV              
       
    

INICIO ENDP
CODIGO ENDS
END INICIO 