Title Practica 3          ;TITULO
DATOS SEGMENT PARA PUBLIC DATA
SEGMENTO1 DB '123456789A'  ;DECLARAMOS LOS TRES SEGMENTOS 
SEGMENTO2 DB '8987654321'
SEGMENTO3 DB 10 DUP('?')

NUMERO DW 10
 
;SEGMENTO3 DB 8 DUP ('?')  


DATOS ENDS 
PILA SEGMENT PARA STACK 'STACK'
    DB 64 DUP('STACK')     
PILA ENDS
CODIGO SEGMENT PARA PUBLIC 'CODE'
INICIO PROC FAR
    PUSH DS
    MOV AX,0
    PUSH AX
    MOV AX, DATOS
    MOV DS, AX
    MOV ES, AX 
;-----------------------
MOV CX, NUMERO 
MOV SI, OFFSET SEGMENTO1
MOV BL, OFFSET SEGMENTO2
MOV DI, OFFSET SEGMENTO3
;LEA SI, SEGMENTO1   ;
;LEA DI, SEGMENTO2

    ;MOV DI, SEGMENTO3
    
REPITE:
;ADD AL,[SI]
;ADD AL,[SI]
;MOV [DI],AL
MOV AL,[SI]
ADD AL,[BX]
MOV [DI],AL

INC SI 
INC DI
DEC CX

JNZ REPITE
    
RET  
INICIO ENDP
CODIGO ENDS
END INICIO
                          
                          