TITLE NUMEROS_PRIMOS_PEREZGARRIDO  

include 'emu8086.inc'


DATOS SEGMENT           
;------------------------------------------------------------------
    ;NUMEROS DB  1,2,3,4,5,6,7,8,9,10,12,11,14,15,16,17;16 DUP(?)
    
    NUMERO_PRIMOS DB 0
     
    NUMERO_NO_PRIMO DB 0
    
    NUMERO_OBTENIDO DB 0 
    
    RESPUESTA DB 0
    
    
DATOS ENDS    

;------------------------------------------------------------------

PILA SEGMENT
    DB 64 DUP(0)
PILA ENDS     

CODIGO SEGMENT
INICIO PROC FAR

    ASSUME DS:DATOS,CS:CODIGO, SS:PILA

        PUSH DS
        MOV  AX,0
        PUSH AX
        MOV AX, DATOS
        MOV DS, AX
        MOV ES, AX  

;----------------------------------------------------------------------

   
REPETICION1: 

REPETICION2:
   
    MOV AX, 0
    
    CALL CLEAR_SCREEN
    GOTOXY 3,4
    CALL PTHIS
    DB 'DETERMINEMOS SI ES UN NUMERO PRIMO O NO',0
    
    
    ;Vamos a pedir numero
    GOTOXY 5,6
    CALL PTHIS
    DB 'INGRESA EL NUMERO ',0
    CALL SCAN_NUM
    MOV NUMERO_OBTENIDO, CL
      
    
    

    
    MOV BL,1
    MOV AL, NUMERO_OBTENIDO;NUMEROS[SI] ;PASAMOS A AL EL NUMERO QUE INDICA NUESTRO INDICE
    CMP AL, 2
    JE  PARPRIMO ;SALTA A ESTA ETIQUETA Y EL NUMERO PAR QUE ES PRIMO ES 2
    JA  PRIMO    ; SI ES MAYOR SALTA A ESTA ETIQUETA
    JB  GUARDARNOPRIMO  ;SI ES MENOR SALATA A ESTA ETIQUETA  
 
 PRIMO:
    MOV AX,0
    MOV AL, NUMERO_OBTENIDO;NUMEROS[SI] ;PASAMOS A AL EL NUMERO QUE INDIQUE NUESTRO INDICE
    INC BL ;
    DIV BL ;  AX ES EL DIVIDENDO Y BL EL DIVISOR
    CMP AH, 0;AQUI SE ALMACENA EL RESIDUO Y SI ES IGUAL A 0 ES NUMERO PAR
    JE GUARDARNOPRIMO
    JA CONTADOR
 
 CONTADOR:
    MOV CL, NUMERO_OBTENIDO;NUMEROS[SI]
    SUB CL,3
    JMP PRIMOVERIFICAR
 
 PRIMOVERIFICAR:
    MOV AX,0
    MOV AL, NUMERO_OBTENIDO;NUMEROS[SI] ;PASAMOS A AL EL NUMERO QUE INDICA NUESTRO INDICE
    CMP AL,3
    JE PRIMO_TRES
    INC BL ;INCREMENTAMOS BL
    DIV BL ;DIVIDIMOS ENTRE BL
    CMP AH, 0       ;SI EL RESIDUO ES MAYOR A 0
    JE GUARDARNOPRIMO  ;HACE EL CICLO HASTA BUSCAR UN NUMERO QUE SE DIVIDA EXACTO Y SI ES ASI LO GUARDA
    LOOP PRIMOVERIFICAR  
 
 
 GUARDAR_PRIMO:
    MOV AL, NUMERO_OBTENIDO;NUMEROS[SI];PASA EL NUMERO A AL 
    MOV NUMERO_PRIMOS,AL  ;[DI]; Y LO PASA CON SU ETIQUETA DEL INDICE DE DESTINO

    CMP AL,NUMERO_PRIMOS
    JE EXIT0
  
 
 PARPRIMO: 
    MOV NUMERO_PRIMOS,AL ;[DI]
    
    CMP AL, NUMERO_PRIMOS
    JE EXIT1
    
 PRIMO_TRES:
    MOV NUMERO_PRIMOS, AL
    CMP AL, NUMERO_PRIMOS
    JE EXIT2
    
 
 GUARDARNOPRIMO: 
    MOV AL, NUMERO_OBTENIDO;NUMEROS [SI]
    MOV NUMERO_NO_PRIMO, AL ;[DI], AL   
    
    CMP AL, NUMERO_NO_PRIMO
    JE EXIT3
    

    
    EXIT0:
    EXIT1:
    EXIT2:
      
      GOTOXY 7,8
      CALL PTHIS
      DB 'EL NUMERO ES PRIMO, PORQUE ES DIVISIBLE ENTRE 1 Y EL MISMO ',0  
      
      
      GOTOXY 7,9                   ;INDICAMOS LA POSICION DE CURSOR CAMBIANDO EN CADA VUELTA EN FUNCION DE LA VARIABLE CONT.
      MOV AX,0                        ;LIMPIAMOS AX
      MOV AL, NUMERO_PRIMOS         ;INDICAMOS LA POSICION DEL ARREGLO EN DONDE DESEAMOS OBTENER EL VALOR.
      CALL PRINT_NUM                    ;IMPRIMIMOS EL NUMERO EN PANTALLA.
      
      
      GOTOXY 10,10
      CALL PTHIS
      DB 'DESEA VOLVER A CALCULAR SI EL NUMERO ES PRIMO: SI = 2, NO = 1 ',0
      CALL SCAN_NUM
      MOV RESPUESTA, CL
      
      LOOP REPETICION1
      CMP CL,2
      JE TERMINO1 
                   
      
    EXIT3: 
    
      GOTOXY 7,8
      CALL PTHIS
      DB 'EL NUMERO NO ES PRIMO, PORQUE TIENE MAS DE DOS DIVISORES  ',0  
      
      GOTOXY 8,9                    ;INDICAMOS LA POSICION DE CURSOR CAMBIANDO EN CADA VUELTA EN FUNCION DE LA VARIABLE CONT.
      MOV AX,0                        ;LIMPIAMOS AX
      MOV AL, NUMERO_NO_PRIMO         ;INDICAMOS LA POSICION DEL ARREGLO EN DONDE DESEAMOS OBTENER EL VALOR.
      CALL PRINT_NUM         
      
      GOTOXY 10,10
      CALL PTHIS
      DB 'DESEA VOLVER A CALCULAR SI EL NUMERO ES PRIMO: SI = 2, NO = 1 ',0
      CALL SCAN_NUM
      MOV RESPUESTA, CL
      
      LOOP REPETICION2
      CMP CL,2
      JE TERMINO2
      
    
 TERMINO1:
 TERMINO2:
 
 RET
    
    
INICIO ENDP

CODIGO ENDS

    DEFINE_PTHIS
    DEFINE_CLEAR_SCREEN
    DEFINE_SCAN_NUM
    DEFINE_PRINT_NUM_UNS
    DEFINE_PRINT_STRING
    DEFINE_PRINT_NUM 

    END INICIO  